name: test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    
    - name: echo
      if: ${{ matrix.os }} == ubuntu-latest
      run: |
        echo "hello"
