name: test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    
    - name: echo
      if: matrix.os == 'ubuntu-latest'
      run: |
        echo "hello"
        echo %{{ matrix.os }}
    - name: echo true
      if: ${{ matrix.os == 'ubuntu-latest' && 1 == 1}}
      run: |
        echo "hello2"
        echo %{{ matrix.os }}
    - name: echo false
      if: ${{ matrix.os == 'ubuntu-latest' && 1 == 2}}
      run: |
        echo "hello3"
        echo %{{ matrix.os }}
